### ISSUE TITLE
no data for characters from server with a hyphen "-" in the name

### ISSUE THREAD

**Issue by Like2w** [tfmonk/Accountant#11]
There is no data for characters from ru server "Король-лич" in English it is "Lich King" server name. On other servers everything works fine. 

logged on my alt Шордуум-Король-лич:
![image](https://user-images.githubusercontent.com/119116837/204091945-2d9d7879-242c-48bb-b445-dc25f842c9ab.png)

logged on main from another server Ревущий фьорд (Howling fjord):
![image](https://user-images.githubusercontent.com/119116837/204092184-a49ac924-2256-46cd-8933-60379700b34f.png)

Version:
 - Accountant-10.1.1

**Comment by tfmonk** [comment]
Thanks for the report @Like2w 

I can replicate the issue and believe I have a fix that could work for it, it appears "-" is a special character so we can find and replace it on the realm name, I'm just testing a fix which seems to be working.

However it wont restore any historical data, due to the fix changing the realm name, it can be manually restored by changing the accountant.lua in WTF\Account\<ACCOUNTNAME>\SavedVariables by doing a find on replace on the realm name with a - in.. for example realm-name to realmname and then that would allow the data (if any to display)

**Comment by Like2w** [comment]
That helped! I am very grateful!

**Comment by tfmonk** [comment]
@Like2w let me know if you have any other issues, I'm still  testing/validating before i add it to a version to test (with df launch dont have the time to do a alpha build to test at the moment)
