### ISSUE TITLE
Across all realms

### ISSUE THREAD

**Issue by DravenSA** [tfmonk/Accountant#16]
Basically, I have 49 characters,
23 on one realm, 20 on another realm and the remainder on a few others.
Would it not be possible to be able to see ALL the gold on all the characters on all the realms as right now i can only see the 23 that on my main realm.
and then i have to change realm so see the gold on the other 20 characters and so on.

I find this very useful as i can see exactly how much i have made across ALL my toons in one easy place. I have an addon that shows me all their gold across all the realms, but not how much each have this day or week. like Accountant does.

**Comment by tfmonk** [comment]
@DravenSA It might be possible, I would need to look into how the accountant data is stored to see and see if its possible to add a realm drop down option in and then possible an all realm option but that would be a fairly big change i think but potentially doable, but there is a slight bug still that needs to be resolved with the All chars tab is limited to the first 15 chars  to be displayed but total gold figures are for all chars selected, it's limited as I am having issues adding scroll functionality in due to the way the addon was created
